#!/bin/bash
# Builds "CX Briefing.app" using osacompile (built into macOS — no extra tools needed).
# Run this once per machine, or after moving the cx-briefing folder.
#
# Usage:  bash build-app.sh
#         bash build-app.sh --dest ~/Applications

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DEST="$SCRIPT_DIR"
if [[ "${1:-}" == "--dest" && -n "${2:-}" ]]; then DEST="$2"
elif [[ "${1:-}" == --dest=* ]]; then DEST="${1#--dest=}"; fi

APP_PATH="$DEST/CX Briefing.app"
QUERY_NEW_URL="${QUERY_NEW_URL:-https://query.new/}"
QUERY_DASHBOARD_URL="${QUERY_DASHBOARD_URL:-https://query-new.utility.stackblitz.dev/dashboard/ba70a056-06d3-4a46-8340-6d18ac188683?chat=collapsed}"
QUERY_TICKET_ANALYZER_URL="${QUERY_TICKET_ANALYZER_URL:-https://query-new.utility.stackblitz.dev/workflows/7ccc7ec0-0de6-4ab2-a5e7-c9c178d29f43/798873df-143f-4632-ac45-ee417a68a47a}"

# ── Find node ──────────────────────────────────────────────────
NODE=""
for C in "$(command -v node 2>/dev/null || true)" "/opt/homebrew/bin/node" "/usr/local/bin/node" "$HOME/.volta/bin/node"; do
  [[ -x "$C" ]] && NODE="$C" && break
done
[[ -z "$NODE" ]] && echo "❌  Node.js not found." && exit 1
echo "✓  Node: $NODE"

# ── Write AppleScript ──────────────────────────────────────────
SCRIPT_SRC="$(mktemp /tmp/cx-briefing-XXXXXX.applescript)"
cat > "$SCRIPT_SRC" << APPLESCRIPT_EOF
-- CX Briefing — generated by build-app.sh
-- Flow: fetch Front data → build prompt → open Claude Desktop → paste → watch for HTML output

property projectPath : "$SCRIPT_DIR"
property nodePath : "$NODE"
property hours : "16"
property queryNewURL : "$QUERY_NEW_URL"
property queryDashboardURL : "$QUERY_DASHBOARD_URL"
property queryTicketAnalyzerURL : "$QUERY_TICKET_ANALYZER_URL"
-- Output path is set per run (see on run): ~/cx-briefing-output.html so the
-- same path is visible to Claude Write and to `open` (avoids /tmp edge cases).

on run
  -- Per-user path; must match what we tell Claude in STEP 4
  set outputPath to do shell script "printf '%s/cx-briefing-output.html' \"$HOME\""
  set envFile to projectPath & "/.env"

  -- Check .env
  try
    do shell script "test -f " & quoted form of envFile
  on error
    display alert "CX Briefing — Setup Required" message "No .env file found." & return & "Run: bash " & projectPath & "/team-setup.sh" as critical buttons {"Open Folder", "OK"} default button "OK"
    if button returned of result is "Open Folder" then do shell script "open " & quoted form of projectPath
    return
  end try

  -- Remove stale output file so we can detect when Claude writes a new one
  do shell script "rm -f " & quoted form of outputPath

  display notification "Fetching Front ticket data..." with title "CX Briefing" subtitle "Step 1 of 2"

  -- Fetch Front summary via node
  set frontCmd to "/bin/bash -c 'set -a && . " & quoted form of envFile & " && set +a && " & quoted form of nodePath & " " & quoted form of (projectPath & "/index.js") & " --mode=front-summary 2>/dev/null'"
  set frontSummary to ""
  try
    set frontSummary to do shell script frontCmd
  on error
    set frontSummary to "(Front data unavailable)"
  end try

  -- Build the prompt for Claude Desktop
  set thePrompt to "You are generating a CX daily briefing for the bolt.new support team. Today is " & (do shell script "date '+%A %B %d, %Y %H:%M'") & ". Cover the last " & hours & " hours.

STEP 1 — Read Slack channels
Use the Slack MCP tools to read messages from these channels. For each channel identify: incidents/outages, messages needing a CX reply, product changes, important announcements.

Channels (read ALL of them):
- bolt-bugs (critical — bugs & outages)
- cx-core (high — CX team discussions)
- cx-team (high — team updates & escalations)
- product-releases (high — product changes & deploys)
- announcements (high — company announcements)
- bolt-eng-support (medium — engineering signals for CX)
- ext-parahelp-stackblitz (medium — support patterns)
- general (low — general chat)

STEP 2 — Front support queue (already fetched, include this in the briefing):
" & frontSummary & "

STEP 3 — Generate a complete self-contained HTML briefing file.
The HTML must have inline CSS only (no external dependencies) and include:
- Dark header (#0f172a) with title 'CX Briefing', date, and status badge (NORMAL/ELEVATED/INCIDENT)
- Quick links row near the top with:
  - Query.new: \" & queryNewURL & \"
  - Query Dashboard: \" & queryDashboardURL & \"
  - Ticket Analyzer: \" & queryTicketAnalyzerURL & \"
- Bold summary box: 2-3 sentence shift overview
- 'Needs Reply' section with Slack threads/messages that need a CX response (this is the most important section — highlight prominently)
- Priority Actions: numbered list of top 5 things the team must know or do right now
- Cards for: Incidents & Bugs | Product Updates | CX Highlights | Support Queue | Engineering Signals
- Each card shows relevant items with timestamps. Empty cards show 'All quiet'.

STEP 4 — Save the file
Use the Write tool to save the complete HTML to exactly this path: " & outputPath & "
After saving output only this line: FILE:" & outputPath

  -- Copy prompt to clipboard
  set the clipboard to thePrompt

  -- Open Claude Desktop with a new chat
  display notification "Opening Claude Desktop for Slack briefing..." with title "CX Briefing" subtitle "Step 2 of 2 — may take several minutes"
  do shell script "open 'claude://new'"
  delay 3

  -- Paste and submit
  tell application "System Events"
    tell process "Claude"
      set frontmost to true
      delay 0.5
      keystroke "v" using command down
      delay 0.8
      key code 36 -- Return/Enter
    end tell
  end tell

  -- Watch for the output file (Slack + HTML often exceeds 3 min — allow 20 min)
  set maxWait to 1200
  set waited to 0
  repeat while waited < maxWait
    delay 2
    set waited to waited + 2
    try
      do shell script "test -f " & quoted form of outputPath & " && test -s " & quoted form of outputPath
      delay 1
      do shell script "open " & quoted form of outputPath
      display notification "Dashboard opened in your browser!" with title "CX Briefing" subtitle "Ready!"
      return
    end try
  end repeat

  -- Claude may finish in the last few seconds after the loop
  try
    do shell script "test -f " & quoted form of outputPath & " && test -s " & quoted form of outputPath
    do shell script "open " & quoted form of outputPath
    display notification "Dashboard opened in your browser!" with title "CX Briefing" subtitle "Ready (detected right after wait)"
    return
  end try

  -- Still no file: remind where it should be + optional manual open
  display notification "No file yet at ~/cx-briefing-output.html — check Claude Write tool" with title "CX Briefing" subtitle "Ask Claude to save HTML to that path, then open it"
  tell application "Claude" to activate
end run
APPLESCRIPT_EOF

# ── Compile ────────────────────────────────────────────────────
echo "→ Compiling CX Briefing.app..."
rm -rf "$APP_PATH"
osacompile -o "$APP_PATH" "$SCRIPT_SRC"
rm -f "$SCRIPT_SRC"
xattr -cr "$APP_PATH" 2>/dev/null || true

echo "✅  Built: $APP_PATH"
echo ""
echo "  Double-click to run. Drag to Dock for easy access."
echo "  To install to ~/Applications: bash build-app.sh --dest ~/Applications"
