#!/bin/bash
# Builds "CX Briefing.app" using osacompile (built into macOS — no extra tools needed).
# Run this once per machine, or after moving the cx-briefing folder.
#
# Usage:  bash build-app.sh
#         bash build-app.sh --dest ~/Applications

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DEST="$SCRIPT_DIR"
if [[ "${1:-}" == "--dest" && -n "${2:-}" ]]; then DEST="$2"
elif [[ "${1:-}" == --dest=* ]]; then DEST="${1#--dest=}"; fi

APP_PATH="$DEST/CX Briefing.app"
QUERY_NEW_URL="${QUERY_NEW_URL:-https://query.new/}"
QUERY_DASHBOARD_URL="${QUERY_DASHBOARD_URL:-https://query-new.utility.stackblitz.dev/dashboard/ba70a056-06d3-4a46-8340-6d18ac188683?chat=collapsed}"
QUERY_TICKET_ANALYZER_URL="${QUERY_TICKET_ANALYZER_URL:-https://query-new.utility.stackblitz.dev/workflows/7ccc7ec0-0de6-4ab2-a5e7-c9c178d29f43/798873df-143f-4632-ac45-ee417a68a47a}"

# ── Find node ──────────────────────────────────────────────────
NODE=""
for C in "$(command -v node 2>/dev/null || true)" "/opt/homebrew/bin/node" "/usr/local/bin/node" "$HOME/.volta/bin/node"; do
  [[ -x "$C" ]] && NODE="$C" && break
done
[[ -z "$NODE" ]] && echo "❌  Node.js not found." && exit 1
echo "✓  Node: $NODE"

# ── Write AppleScript ──────────────────────────────────────────
# mktemp(1) on macOS: the final path component must end with six+ literal X's (no suffix after them).
SCRIPT_SRC="$(mktemp "${TMPDIR:-/tmp}/cx-briefing.XXXXXX")"
cat > "$SCRIPT_SRC" << APPLESCRIPT_EOF
-- CX Briefing — generated by build-app.sh
-- Flow: fetch Front data → copy prompt → open Claude Desktop → auto-paste (⌘V + Enter) → watch for HTML output
-- Auto-paste uses System Events → requires CX Briefing in System Settings → Privacy & Security → Accessibility.
-- If macOS returns error 1002 anyway: remove CX Briefing from Accessibility, run bash build-app.sh, re-add the .app, restart.

property projectPath : "$SCRIPT_DIR"
property nodePath : "$NODE"
property hours : "16"
property queryNewURL : "$QUERY_NEW_URL"
property queryDashboardURL : "$QUERY_DASHBOARD_URL"
property queryTicketAnalyzerURL : "$QUERY_TICKET_ANALYZER_URL"
-- Output file lives IN the cx-briefing folder: Claude Desktop's Write tool
-- often cannot save under $HOME (sandbox); project paths usually work.

-- Return true if keystrokes were sent; otherwise throws (caller shows manual-paste alert).
on pasteIntoClaudeAndSubmit()
  repeat with attempt from 1 to 10
    tell application "System Events"
      if exists process "Claude" then
        tell process "Claude"
          set frontmost to true
          delay 0.45
          keystroke "v" using command down
          delay 0.8
          key code 36 -- Return / Enter
        end tell
        return true
      else if exists process "Claude Desktop" then
        tell process "Claude Desktop"
          set frontmost to true
          delay 0.45
          keystroke "v" using command down
          delay 0.8
          key code 36
        end tell
        return true
      end if
    end tell
    delay 0.6
  end repeat
  error "Claude window not ready for paste" number 1001
end pasteIntoClaudeAndSubmit

on run
  set outputPath to projectPath & "/cx-briefing-output.html"
  set envFile to projectPath & "/.env"

  -- Check .env
  try
    do shell script "test -f " & quoted form of envFile
  on error
    display alert "CX Briefing — Setup Required" message "No .env file found." & return & "Run: bash " & projectPath & "/team-setup.sh" as critical buttons {"Open Folder", "OK"} default button "OK"
    if button returned of result is "Open Folder" then do shell script "open " & quoted form of projectPath
    return
  end try

  repeat
    set cycleResult to my runOneBriefingCycle(outputPath, envFile)
    if cycleResult is "success" then
      try
        set d to display dialog "Briefing opened in your browser. Fetch again (full Front + Claude flow)?" buttons {"Done", "Fetch again"} default button "Fetch again" with title "CX Briefing"
        if button returned of d is "Done" then exit repeat
      on error number -128
        exit repeat
      end try
    else
      try
        set d to display dialog "No briefing HTML detected (timeout or Claude still writing). Try the full run again?" buttons {"Quit", "Try again"} default button "Try again" with title "CX Briefing"
        if button returned of d is "Quit" then exit repeat
      on error number -128
        exit repeat
      end try
    end if
  end repeat
end run

on runOneBriefingCycle(outputPath, envFile)
  -- Remove stale output file so we can detect when Claude writes a new one
  do shell script "rm -f " & quoted form of outputPath

  display notification "Fetching Front ticket data..." with title "CX Briefing" subtitle "Step 1 of 2"

  -- Fetch Front summary via node
  set frontCmd to "/bin/bash -c 'set -a && . " & quoted form of envFile & " && set +a && " & quoted form of nodePath & " " & quoted form of (projectPath & "/index.js") & " --mode=front-summary 2>/dev/null'"
  set frontSummary to ""
  try
    set frontSummary to do shell script frontCmd
  on error
    set frontSummary to "(Front data unavailable)"
  end try

  -- Build the prompt for Claude Desktop
  set thePrompt to "You are generating a CX daily briefing for the bolt.new support team. Today is " & (do shell script "date '+%A %B %d, %Y %H:%M'") & ". Cover the last " & hours & " hours.

STEP 1 — Read Slack channels
Use the Slack MCP tools to read messages from these channels. For each channel identify: incidents/outages, messages needing a CX reply, product changes, important announcements.

Channels (read ALL of them):
- bolt-bugs (critical — bugs & outages)
- cx-core (high — CX team discussions)
- cx-team (high — team updates & escalations)
- product-releases (high — product changes & deploys)
- announcements (high — company announcements)
- bolt-eng-support (medium — engineering signals for CX)
- ext-parahelp-stackblitz (medium — support patterns)
- general (low — general chat)

STEP 2 — Front support queue (already fetched, include this in the briefing):
" & frontSummary & "

STEP 3 — Generate a complete self-contained HTML briefing file.
The HTML must have inline CSS only (no external dependencies) and include:
- Dark header (#0f172a) with title 'CX Briefing', date, and status badge (NORMAL/ELEVATED/INCIDENT)
- Quick links row near the top with:
  - Query.new: \" & queryNewURL & \"
  - Query Dashboard: \" & queryDashboardURL & \"
  - Ticket Analyzer: \" & queryTicketAnalyzerURL & \"
- Bold summary box: 2-3 sentence shift overview
- 'Needs Reply' section with Slack threads/messages that need a CX response (this is the most important section — highlight prominently)
- Priority Actions: numbered list of top 5 things the team must know or do right now
- Cards for: Incidents & Bugs | Product Updates | CX Highlights | Support Queue | Engineering Signals
- Each card shows relevant items with timestamps. Empty cards show 'All quiet'.

STEP 4 — Save the file (Write tool only)
Save the complete HTML to exactly this path (POSIX, do not change it — do not use ~/ or a Cowork outputs folder; if Write is denied, add this cx-briefing folder as a project in Claude Desktop and retry):
" & outputPath & "
After saving output only this line: FILE:" & outputPath

  -- Copy prompt to clipboard
  set the clipboard to thePrompt

  -- Open Claude Desktop with a new chat
  display notification "Opening Claude Desktop for Slack briefing..." with title "CX Briefing" subtitle "Step 2 of 2 — may take several minutes"
  do shell script "open 'claude://new'"
  delay 2.5
  try
    tell application "Claude" to activate
  on error
    try
      tell application "Claude Desktop" to activate
    end try
  end try

  set pasteErrNum to 0
  set didPaste to false
  try
    set didPaste to my pasteIntoClaudeAndSubmit()
  on error errMsg number errNum
    set pasteErrNum to errNum
    set didPaste to false
  end try

  if didPaste then
    display notification "Pasted briefing into Claude — waiting for HTML (up to 20 min)…" with title "CX Briefing" subtitle "Step 2 of 2"
  else
    try
      tell application "Claude" to activate
    on error
      try
        tell application "Claude Desktop" to activate
      end try
    end try
    display alert "CX Briefing — paste manually" message "Auto-paste did not run (error " & pasteErrNum & "). The full prompt is on the clipboard." & return & return & "In Claude: ⌘V, then Enter." & return & return & "If this used to work: System Settings → Privacy & Security → Accessibility → remove CX Briefing, run bash build-app.sh from the cx-briefing folder, add the new CX Briefing.app again, enable it, then quit and reopen the app (rebuilds refresh the app signature TCC uses)." as informational buttons {"OK"} default button "OK"
    display notification "Waiting for HTML — paste in Claude if you have not yet (⌘V, Enter)" with title "CX Briefing" subtitle "Up to 20 min"
  end if

  -- Watch for the output file (Slack + HTML often exceeds 3 min — allow 20 min)
  set maxWait to 1200
  set waited to 0
  repeat while waited < maxWait
    delay 2
    set waited to waited + 2
    try
      do shell script "test -f " & quoted form of outputPath & " && test -s " & quoted form of outputPath
      delay 1
      do shell script "open " & quoted form of outputPath
      display notification "Dashboard opened in your browser!" with title "CX Briefing" subtitle "Ready!"
      return "success"
    end try
  end repeat

  -- Claude may finish in the last few seconds after the loop
  try
    do shell script "test -f " & quoted form of outputPath & " && test -s " & quoted form of outputPath
    do shell script "open " & quoted form of outputPath
    display notification "Dashboard opened in your browser!" with title "CX Briefing" subtitle "Ready (detected right after wait)"
    return "success"
  end try

  -- Fallbacks if Write used another path (older prompts or sandbox quirks)
  set homeOut to do shell script "printf '%s/cx-briefing-output.html' \"$HOME\""
  set fallbackList to {homeOut, "/tmp/cx-briefing-output.html"}
  repeat with altPath in fallbackList
    set p to contents of altPath
    try
      do shell script "test -f " & quoted form of p & " && test -s " & quoted form of p
      do shell script "open " & quoted form of p
      display notification "Dashboard opened (fallback path)" with title "CX Briefing" subtitle p
      return "success"
    end try
  end repeat

  display notification "No briefing HTML found — check Write tool" with title "CX Briefing" subtitle "Expected: cx-briefing-output.html in project folder"
  tell application "Claude" to activate
  return "fail"
end runOneBriefingCycle
APPLESCRIPT_EOF

# ── Compile ────────────────────────────────────────────────────
echo "→ Compiling CX Briefing.app..."
rm -rf "$APP_PATH"
osacompile -o "$APP_PATH" "$SCRIPT_SRC"
rm -f "$SCRIPT_SRC"
xattr -cr "$APP_PATH" 2>/dev/null || true

echo "✅  Built: $APP_PATH"
echo ""
echo "  Double-click to run. Drag to Dock for easy access."
echo "  To install to ~/Applications: bash build-app.sh --dest ~/Applications"
